name = "van-beach"
compatibility_date = "2026-02-01"
pages_build_output_dir = "client/dist"

[[kv_namespaces]]
binding = "BEACH_CACHE"
id = "d3f1191b50b34b749b5d2999e22b540d"
preview_id = "0a8235f0fd0f4914b7ad8430e17f1fcd"
